server:
  port: 8080

spring:
  datasource:
    url: jdbc:hsqldb:file:./target/hsqldb-server/bookcollectordb;DB_CLOSE_DELAY=-1
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update